# {json:scada} docker demo - create the .env file with a unique random JWT secret.
#
# The JWT secret signs the auth tokens of server_realtime_auth. A shared or
# publicly known secret lets anyone forge an admin token and take control of
# the system, so every installation must have its own.
#
# Usage: .\generate-env.ps1 [-Force]

param([switch]$Force)

$ErrorActionPreference = 'Stop'

$envFile = Join-Path $PSScriptRoot '.env'

if ((Test-Path $envFile) -and (-not $Force)) {
    Write-Host "$envFile already exists, keeping it untouched."
    Write-Host "Use '.\generate-env.ps1 -Force' to replace it with a new secret"
    Write-Host "(all users will have to log in again)."
    exit 0
}

$bytes = New-Object byte[] 48
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }
$secret = -join ($bytes | ForEach-Object { $_.ToString('x2') })

$content = @"
# {json:scada} docker demo environment - generated by generate-env.ps1
# KEEP THIS FILE PRIVATE AND OUT OF VERSION CONTROL.
# See .env.example for the meaning of each variable.

JS_JWT_SECRET=$secret
JS_BIND_ADDR=127.0.0.1
"@

# write with LF endings so the file parses the same way on every platform
$content = $content -replace "`r`n", "`n"
[System.IO.File]::WriteAllText($envFile, $content + "`n", (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Created $envFile with a new random JS_JWT_SECRET."
Write-Host "Published ports are bound to 127.0.0.1; edit JS_BIND_ADDR in $envFile to change that."
