#!/bin/sh
# {json:scada} docker demo - create the .env file with a unique random JWT secret.
#
# The JWT secret signs the auth tokens of server_realtime_auth. A shared or
# publicly known secret lets anyone forge an admin token and take control of
# the system, so every installation must have its own.
#
# Usage: ./generate-env.sh [--force]

set -e

cd "$(dirname "$0")"
ENV_FILE=".env"

if [ -f "$ENV_FILE" ] && [ "$1" != "--force" ]; then
    echo "$ENV_FILE already exists, keeping it untouched."
    echo "Use './generate-env.sh --force' to replace it with a new secret"
    echo "(all users will have to log in again)."
    exit 0
fi

if [ -r /dev/urandom ]; then
    SECRET=$(head -c 48 /dev/urandom | od -An -tx1 | tr -d ' \n')
elif command -v openssl > /dev/null 2>&1; then
    SECRET=$(openssl rand -hex 48)
else
    echo "ERROR: no source of randomness found (/dev/urandom or openssl)." >&2
    exit 1
fi

if [ ${#SECRET} -lt 32 ]; then
    echo "ERROR: failed to generate a secret of sufficient length." >&2
    exit 1
fi

umask 077
cat > "$ENV_FILE" <<EOF
# {json:scada} docker demo environment - generated by generate-env.sh
# KEEP THIS FILE PRIVATE AND OUT OF VERSION CONTROL.
# See .env.example for the meaning of each variable.

JS_JWT_SECRET=$SECRET
JS_BIND_ADDR=127.0.0.1
EOF

echo "Created $ENV_FILE with a new random JS_JWT_SECRET."
echo "Published ports are bound to 127.0.0.1; edit JS_BIND_ADDR in $ENV_FILE to change that."
