/*
 * Customizable processor of mongodb changes via change streams.
 * DO NOT EDIT THIS FILE! CUSTOMIZE THE customized_module.js file
 * {json:scada} - Copyright (c) 2020-2026 - Ricardo L. Olsen
 * This file is part of the JSON-SCADA distribution (https://github.com/riclolsen/json-scada).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

import { Log, ConnectionManager } from './jsonscada/index.js'
import { CustomProcessor } from './customized_module.js'

process.on('uncaughtException', (err: Error) => Log.log('Uncaught Exception:' + JSON.stringify(err)))

const mgr = new ConnectionManager({ manageRedundancy: true })

mgr.run(() => {
  CustomProcessor(mgr)
})
